config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }
  root to: 'books#index'
  get '/books/:id', to: 'books#show', as: 'show_book'
  post '/books/:id/order', to: 'books#order', as: 'create_order'
  post 'books/:id/checkout', to: 'books#checkout', as: 'create_checkout'
  get 'carts', to: 'books#carts', as: 'carts'
  get 'orders', to: 'books#orders', as: 'orders'
  get 'orders/:id/edit', to: 'books#edit', as: 'edit_order'
  post 'orders/:id', to:	'books#update', as: 'update_order'
  delete 'orders/:id', to: 'books#destroy', as: 'cancel_order'
  delete 'cart_remove/:book_id', to: 'books#cart_remove', as: 'cart_remove'
  post 'create_cart', to: 'books#create_cart', as: 'create_carts'
  get 'complete', to: 'books#complete', as: 'complete'
end

app/models/book.rb
class Book < ApplicationRecord
  def self.search(search) 
    if search 
      Book.where(["book_title LIKE ?", "%#{search}%"])
    else
      Book.all
    end
  end
end

app/controllers/books_controller.rb
require 'date'
class BooksController < ApplicationController
  before_action :set_params, only: [:show, :order, :checkout]
  before_action :carts, only: [:create_cart]
  def index
    @books = Book.all.search(params[:search_value]).paginate(page: params[:page], per_page: 8)
  end

  def show
    @current_date = DateTime.now
    @delivery_time = @current_date + 3.days
    @quantity = 1
    @quantity = params[:quantity] unless params[:quantity].blank?
  end

  def order
    # redirect login
    @param_data = params[:book]
    redirect_to new_user_session_path(origin: show_book_path, quantity: @param_data[:quantity]) unless user_signed_in?

    @delivery_time = @param_data[:delivery_time]
    @quantity = @param_data[:quantity]

    # check add_cart
    if @param_data[:add_cart].to_i == 1 && user_signed_in?
      # save cookies
      @carts = []
      cookie_carts = cookies[:carts]
      if cookie_carts.present? && JSON.parse(cookie_carts).length > 0
        @carts = JSON.parse(cookie_carts).find_all {|cart| cart['user_id'].to_i == current_user.id }
      end
      @carts << {
        user_id: current_user.id,
        book_id: @param_data[:book_id],
        quantity: @param_data[:quantity]
      }
      # save cookies
      cookies[:carts] = {
        value: JSON.generate(@carts),
        expires: 1.week
      }
      cookies[:cart_total] = @carts.length
      # redierct
      redirect_to carts_path
    else
      @payment = ['Debit Card', 'Credit Card(Mastercard)', 'Mobile payment', 'Bank transfer']
     
      if @quantity.to_i > 2
        @total_amount = (@book.price * @quantity.to_i)
      else
        @total_amount = (@book.price * @quantity.to_i) + @book.delivery_fee
      end
    end
  end

  def carts
    # get cookies
    cart_list = []
    cookie_carts = cookies[:carts]
    if cookie_carts.present? && JSON.parse(cookie_carts).length > 0
      cart_list = JSON.parse(cookie_carts).find_all {|cart| cart['user_id'].to_i == current_user.id }
    end
    @carts = []
    @sub_total = 0
    cart_list.each do |cart|
      book = Book.find(cart['book_id'])
      if cart['quantity'].to_i > 2
        @total_amount = (book[:price] * cart['quantity'].to_i)
      else
        @total_amount = (book[:price] * cart['quantity'].to_i) + book[:delivery_fee]
      end
      @sub_total += @total_amount
      @delivery_time = DateTime.now + 3.days
      @payment = ['Debit Card', 'Credit Card(Mastercard)', 'Mobile payment', 'Bank transfer']
        @carts << {
        book_id: book[:id],
        book_title: book[:book_title],
        image: book[:image],
        delivery_time: @delivery_time,
        total_amount: @total_amount,
        quantity: cart['quantity'],
        user_id: cart['user_id']
      }
    end
  end

  def create_cart
    payment = Payment.new(
      user_id: params[:user_id],
      payment_type: params[:payment_type]
    )
    if payment.save
      @carts.each do |cart|
        Order.new(
          user_id: cart[:user_id],
          book_id: cart[:book_id],
          quantity: params[:quantity],
          total_amount: cart[:total_amount],
          delivery_time: cart[:delivery_time],
          payment_id: payment[:id]
        ).save
      end
      # index = 0
      # books = Book.find_by(id: params[:book_id])
      # books.each do |book|
      #   Order.new(
      #     book_id: book['book_id'],
      #     quantity: params[:quantity],
      #     total_amount: params[:total_amount],
      #     user_id: params[:user_id],
      #     delivery_time: params[:delivery_time],
      #     payment_id: payment[:id]
      #   ).save
      # end
      # index += 1
      # cookies clear
      cookies[:carts] = []
      cookies[:cart_total] = nil
      redirect_to complete_path
    end
  end

  def cart_remove
    # get cookies
    @carts = []
    cookie_carts = cookies[:carts]
    if cookie_carts.present? && JSON.parse(cookie_carts).length > 0
      @carts = JSON.parse(cookie_carts).find_all {|cart| cart['book_id'].to_i != params[:book_id].to_i}
    end

    # save cookies
    cookies[:carts] = {
      value: JSON.generate(@carts),
      expires: 1.week
    }
    cookies[:cart_total] = @carts.length
    # redierct
    redirect_to carts_path
  end

  def checkout
    @payment = Payment.new(
      user_id: current_user.id,
      payment_type: params[:do_order][:payment_type]
    )

    if @payment.save
      Order.new(
        user_id: current_user.id,
        book_id: params[:do_order][:book_id],
        quantity: params[:do_order][:quantity],
        total_amount: params[:do_order][:total_amount],
        delivery_time: params[:do_order][:delivery_time],
        payment_id: @payment[:id]
      ).save

      # redierct
      flash.now[:notice] = "Successful order and payment create."
      redirect_to orders_path 
    else
      flash.now[:alert] = "Create failed!"
      render :order
    end
  end

  def orders
    @order_list = Order.select('
      orders.id,
      orders.book_id,
      orders.created_at,
      orders.delivery_time,
      orders.total_amount,
      orders.quantity,
      payments.payment_type,
      users.name,
      users.address,
      books.image
    ').joins('
      LEFT JOIN payments
      ON payments.id = orders.payment_id
      LEFT JOIN users
      ON users.id = orders.user_id
      LEFT JOIN books
      ON books.id = orders.book_id
    ').where(user_id: current_user.id).order('orders.created_at DESC')
  end

  def edit
    @payment = ['Debit Card', 'Credit Card(Mastercard)', 'Mobile payment', 'Bank transfer']
    @order = Order.select('
      orders.id,
      orders.quantity,
      payments.payment_type,
      users.address
    ').joins('
      INNER JOIN payments
      ON payments.id = orders.payment_id
      INNER JOIN users
      ON users.id = orders.user_id
    ').where('orders.id = ?', params[:id]).first
  end

  def update
    @order = Order.find(params[:id])
    @order[:quantity] = params[:quantity]
    @order.payment[:payment_type] = params[:payment_type]
    @order.user[:address] = params[:address]
    if @order.save && @order.payment.save && @order.user.save
      redirect_to orders_path
      flash.now[:notice] = "Successful update!"
    else
      flash.now[:alert] = "Update failed!"
      render :edit
    end
  end

  def destroy
    @order = Order.find(params[:id])
    @order.destroy
      flash[:notice] = "Order deletion completed successfully."
      redirect_to orders_path
  end

  def complete; end
  
  
  def set_params
    @book = Book.find(params[:id])
  end

  def order_params
    params.require(:do_order).permit(:user_id, :book_id, :quantity, :total_amount, :delivery_time, :order_id, :payment_type)
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/carts.html.erb
<%= form_with url: create_carts_path, local: true do |f| %>
  <% if @carts.length.zero? %>
    <div class="d-flex justify-content-center">
      <p class="display-6 text-muted">
      <%= image_tag 'img/shopping.gif', :alt=> "" %>Your Bookstore Cart is Empty</p>
    </div>
  <% else %>
    <div class="container">
      <div class="row justify-content-sm-center">
        <div class="col col-md-3">Subtotal:</div>
        <div class="col col-md-2 bi bi-currency-yen"><td><%= @sub_total %></td></div>
      </div>
      <div class="row justify-content-sm-center">
        <div class="col col-md-3">Delivery Time:</div>
        <div class="col col-md-2"><td><%= @delivery_time.strftime "%A, %m/%d" %></td></div>
      </div>
      <div class="row justify-content-sm-center payment_box">
        <div class="col col-md-3">Payment Method:</div>
        <div class="col col-md-2"><td><%= f.select :payment_type, @payment, :prompt=> 'Add to Payment....' %></td></div>
      </div>
      <div class="row justify-content-center">
        <%= f.submit 'Proceed to checkout  ('+ cookies[:cart_total] +'items)', class: "btn btn-primary col-md-5 mt-2" %>
      </div>
    </div>
    <% @carts.each do |cart| %>
    <div class="d-flex justify-content-center m-3">
      <div class="card mb-3" style="max-width: 500px; background-color: #cbd5e0;">
        <div class="row g-0">
          <div class="col-md-4">
            <%= image_tag("img/#{cart[:image]}", :class=> "img-fluid rounded-start", :alt=> "") %>
            <%= f.hidden_field :book_id, value: cart[:book_id] %>
          </div>
          <div class="col-md-8">
            <div class="card-body">
              <h4 class="card-title"><%= cart[:book_title] %></h4>
              <%= f.hidden_field :book_title, value: cart[:book_title] %>
              <p class="card-text bi bi-currency-yen font-weight-bold"><%= cart[:total_amount] %></p>
              <%= f.hidden_field :total_amount, value: cart[:total_amount] %>
              <%= f.hidden_field :user_id, value: cart[:user_id] %>
              <%= f.hidden_field :delivery_time, value: cart[:delivery_time] %>
              <p class="card-text"><%= f.number_field :quantity, value: cart[:quantity], min: 1, max: 30, style: "width:40%;", required: true %>
              <%= link_to 'Delete', "cart_remove/#{cart[:book_id]}", method: :delete, class: 'btn btn-light btn-sm mx-2' %></p>
            </div>
          </div>
        </div>
      </div>
    </div>  
    <% end %>
  <% end %>
<% end %>

app/views/books/complete.html.erb
<div class="d-flex justify-content-center">
  <p class="display-5 text-muted">
    <%= image_tag 'img/shopping.gif' , :alt=> "" %>Thank you for your order
  </p>
</div>

app/views/books/edit.html.erb
<h3 class="text-center mt-3">Order Update</h3>
  <%= form_with url: update_order_path, local: true do |f| %>
  <div class="mt-4" style="margin-left: 40%;">
    <div class="mb-3">
      <label class="col-md-2 control-label">Quantity</label>
      <%= f.number_field :quantity, value: @order[:quantity], class: "col-md-3" %>
    </div>
    <div class="mb-3">
      <label class="col-md-2 control-label">Payment</label>
      <%= f.select :payment_type, @payment, {selected: @order[:payment_type]}, class: "col-md-3" %>
    </div>
    <div class="mb-3">
      <label class="col-md-2 control-label">Address</label>
      <%= f.text_field :address, value: @order[:address], class: "col-md-3" %>
    </div>
    <div class="mt-3 mx-5">
      <%= link_to 'cancel' , '/' , class: 'btn btn-primary btn-sm' %>
      <%= f.submit 'update' , class: 'btn btn-primary btn-sm mx-3' %>
    </div>
  </div>
  <% end %>

app/views/books/index.html.erb
<section class="bg-color">
  <div class="row">
    <% @books.each do |book| %>
      <div class="col-sm-3 mb-4">
        <div class="card">
          <%= image_tag("img/#{book.image}", :alt=> "", class: "card-img-top", :style=> "height:320px;") %>
            <p class="text-center">
              <%= book.book_title %>
            </p>
            <p class="text-center bi bi-currency-yen">
              <%= book.price %>
            </p>
            <%= link_to 'Buy' , show_book_path(book) , class: "btn btn-success btn-sm rounded-0" %>
        </div>
      </div>
      <% end %>
  </div>
  <div class="pagination justify-content-center">
    <%= will_paginate @books %>
  </div>
  </div>
</section>

app/views/books/order.html.erb
<div class="d-flex justify-content-center">
  <h3 class="text-center">Add Payment</h3>
</div>
<%= form_with scope: :do_order, url: create_checkout_path, local: true do |f| %>
  <div class="d-flex justify-content-center m-3">
    <%= image_tag("img/#{@book.image}", :alt=> "") %>
  </div>
  <table class="table d-flex justify-content-center border-bottom-width-0">
    <tbody>
      <tr>
        <td>Book Title:</td>
        <td>
          <%= @book.book_title %>
            <%= f.hidden_field :book_id, value: @book[:id] %>
        </td>
      </tr>
      <td>Quantity:</td>
      <td>
        <%= @quantity %>
          <%= f.hidden_field :quantity, value: @quantity, required: true %>
      </td>
      </tr>
      </tr>
      <td>Delivery Fee:</td>
      <td>
        <% if @quantity.to_i> 2 %>
          FREE
          <% else %>
            <%= @book.delivery_fee %>
              <% end %>
      </td>
      </tr>
      <tr>
        <td>Total Amount:</td>
        <td class="bi bi-currency-yen">
          <%= @total_amount %>
            <%= f.hidden_field :total_amount, value: @total_amount %>
        </td>
      </tr>
      <tr>
        <td>Payment method:</td>
        <td>
          <%= f.select :payment_type, @payment, :prompt=> 'Add to Payment....' %>
        </td>
      </tr>
    </tbody>
  </table>
  <div class="d-flex justify-content-center m-3">
    <%= f.hidden_field :order_id, value: @book[:id] %>
    <%= f.hidden_field :delivery_time, value: @delivery_time %>
    <%= link_to "Back", show_book_path, class: "btn btn-primary btn-md mx-3 btn_width" %>
    <%= f.submit "Go to checkout" , class: "btn btn-primary btn-md btn_width" %>
  </div>
  <% end %>

app/views/books/orders.html.erb
<% @order_list.each do |list| %>
  <div class="col d-flex justify-content-center">
    <div class="card blist-success mb-3" style="max-width: 560px; background-color: #cbd5e0;">
      <div class="row g-0">
        <div class="col-md-4">
          <%= image_tag("img/#{list.image}", :class=> "img-fluid rounded-start", :alt=> "") %>
        </div>
        <div class="col-md-8">
          <div class="card-body">
            <table class="table">
              <tbody>
                <tr>
                  <td>Arriving:</td>
                  <td class="card-text">
                    <%= list.delivery_time.strftime "%A, %m/%d" %>
                  </td>
                </tr>
                <tr>
                  <td>Customer Name:</td>
                  <td class="card-text">
                    <%= list.name %>
                  </td>
                </tr>
                <tr>
                  <td>Address:</td>
                  <td class="card-text">
                    <%= list.address %>
                  </td>
                </tr>
                <tr>
                  <td>Order Total:</td>
                  <td class="card-text bi bi-currency-yen">
                    <%= list.total_amount %>
                  </td>
                </tr>
                <tr>
                  <td>Payment Method:</td>
                  <td class="card-text">
                    <%= list.payment_type %>
                  </td>
                </tr>
              </tbody>
            </table>
            <% if list.created_at <=list.delivery_time %>
              <%= link_to 'Order Cancel' , "orders/#{list.id}", method: :delete, data:
                {confirm: "Are you sure order cancel?" }, class: 'btn btn-primary btn-sm mx-2' %>
                <%= link_to 'Edit' , "orders/#{list.id}/edit" , class: 'btn btn-primary btn-sm text-white w-25' %>
            <% else %>
              <marquee>
                <p class="text-danger small">注文日が3日を超えましたので編集またはキャンセルできません!</p>
              </marquee>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
  <% end %>

app/views/books/show.html.erb
<div class="d-flex justify-content-center", style="margin-top: -6px;">
  <h3 class="text-center">Show Book Detail</h3>
</div>
<%= form_with scope: :book, url: create_order_path, id: "order_form" , local: true do |f| %>
  <div class="d-flex justify-content-center m-3">
    <%= image_tag("img/#{@book.image}", :alt=> "") %>
  </div>
  <table class="table d-flex justify-content-center order_table">
    <tbody>
      <tr>
        <td>Book Title:</td>
        <td>
          <%= @book.book_title %>
            <%= f.hidden_field :book_id, value: @book[:id] %>
        </td>
      </tr>
      <tr>
        <td>Description:</td>
        <td>
          <%= @book.description %>
        </td>
      </tr>
      <tr>
        <td>Delivery Date:</td>
        <td class="bi bi-calendar-check">
          <%= (@current_date.strftime "%A, %b %d" )+ ' ～ ' +(@delivery_time.strftime " %A, %b %d %H:%M" ) %>
          <%= f.hidden_field :delivery_time, value: @delivery_time %>
        </td>
      </tr>
      <tr>
        <td>Shipping Fee:</td>
        <td class="bi bi-currency-yen">
          <%= @book.delivery_fee %>
        </td>
      </tr>
      <tr>
        <td>Price:</td>
        <td class="bi bi-currency-yen">
          <%= @book.price %>
        </td>
      </tr>
      <td>Quantity:</td>
      <td>
        <%= f.number_field :quantity, value: @quantity, min: 1, max: 30, required: true, style: "width:15%;" %>
      </td>
      </tr>
    </tbody>
  </table>
  <div class="d-flex justify-content-center mb-5">
    <%= f.hidden_field :add_cart, value: 0 %>
    <%= f.button "Buy Now" , class: "btn btn-primary btn-sm btn_width", onclick: "btnBuyNow(this);"%>
    <%= f.button "Add to Cart", class: "btn btn-primary btn-sm btn_width mx-3", onclick: "btnAddCart(this);" %>
  </div>
<% end %>

<script>
  function btnBuyNow() {
    event.preventDefault();
    document.getElementById("book_add_cart").value = 0;
    document.getElementById("order_form").submit();
  }
  function btnAddCart() {
    event.preventDefault();
    document.getElementById("book_add_cart").value = 1;
    document.getElementById("order_form").submit();
  }
</script>