config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }
  root to: 'books#index'
  get '/books/:id', to: 'books#show', as: 'show_book'
  post '/books/:id/order', to: 'books#order', as: 'create_order'
  post 'books/:id/checkout', to: 'books#checkout', as: 'create_checkout'
  get 'carts', to: 'books#carts', as: 'carts'
  get 'orders', to: 'books#orders', as: 'orders'
  get 'orders/:id/edit', to: 'books#edit', as: 'edit_order'
  post 'orders/:id', to:	'books#update', as: 'update_order'
  delete 'orders/:id', to: 'books#destroy', as: 'cancel_order'
  delete 'cart_remove/:book_id', to: 'books#cart_remove', as: 'cart_remove'
  post 'create_cart', to: 'books#create_cart', as: 'create_carts'
  get 'complete', to: 'books#complete', as: 'complete'
end

app/views/layouts/_header.html.erb
<body class="h-100 vstack">
  <nav class="navbar navbar-expand-sm navbar-light bg-light border border-success fixed-top", id="navbar">
    <div class="container-fluid">
      <%= link_to (image_tag 'img/bookstore.png'), '/', :class=> "navbar-brand ps-3" %>
      <%= form_tag root_path, :method => 'get' do %>
        <%= text_field_tag :search_value, params[:search_value], size: 25, placeholder: "Search" %>
        <%= submit_tag 'Search' %>
      <% end %>
        <button class="navbar-toggler"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#navbarNav"
          aria-controls="navbarNav"
          aria-expanded="false"
          aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav ms-auto">
            <li class="nav-item">
              <%= link_to('Home', '/', class: "nav-link bi bi-house-door-fill text-success") %>
            </li>
            <% if user_signed_in? %>
              <li class="nav-item">
                <%= link_to('My Orders', orders_path, class: "nav-link bi bi-card-checklist text-success" ) %>
              </li>
              <li class="nav-item">
                <p class= "bi bi-person-fill text-success mt-2"><%= "Name: #{current_user.name}" %></p>
              </li>
              <li class="nav-item">
              <% if cookies[:cart_total].to_i.zero? %>
                <%= link_to 'Cart', carts_path, class: "nav-link bi bi-cart-plus text-success" %>
              <% else %>
                <%= link_to 'Cart', carts_path, class: "nav-link bi bi-cart-plus text-success" %>
                <span class="position-absolute translate-middle badge rounded-circle bg-danger", style="margin-top: -37px; margin-left: 15px;">
                  <%= cookies[:cart_total] %>
                </span>
              <% end %>
              </li>
              <li class="nav-item">
                <%= link_to 'Logout', '/users/sign_out', method: :delete, class: "nav-link bi bi-box-arrow-right text-success" %>
              </li>
            <% else %>
              <li class="nav-item">
                <%= link_to 'Create Account', '/users/sign_up', class: "nav-link bi bi-person-lines-fill text-success" %>
              </li>
              <li class="nav-item">
                <%= link_to 'Login' , '/users/sign_in', class: "nav-link bi bi-box-arrow-in-right text-success" %>
              </li>
            <% end %>
          </ul>
        </div>
    </div>
  </nav>
</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

  <head>
    <title>OnlineBookstore</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.6.1/font/bootstrap-icons.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container", style="margin-top: 100px;">
    <p><%= notice %></p>
    <p><%= alert %></p>
      <%= yield %>
    </div>
  </body>
</html>